<a href="https://colab.research.google.com/github/Mjcherono/Neural-networks-projecttrials/blob/main/Neural_Networks_II_optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Python programming: Neural Networks II

### Importing Libraries

In [74]:

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
# Import a standardization library
from sklearn.preprocessing import StandardScaler
# Import an Multi-Layer Perceptron Classifier model estimator from Scikit-Learn's neural_network library
from sklearn.neural_network import MLPClassifier

from sklearn.metrics import classification_report,confusion_matrix

### Example 1: Breast Cancer Classificaton


We are going to use a dataset that we have already worked with before for this example. This intentional beacuse as we understand how neural network works (no pun intended) we will aslo get to understand how it performs with respect to other classification techniques. Let's dive in!!

Using the breast cancer dataset, our aim is to classify cancer diagnosis as either Malignant or Benign.

**Loading Data**

In [75]:
# Load data
data = pd.read_csv('http://bit.ly/breast_cancer_dataset')
data

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0      842302         M  ...                  0.11890          NaN
1      842517         M  ...                  0.08902          NaN
2    84300903         M  ...                  0.08758          NaN
3    84348301         M  ...                  0.17300          NaN
4    84358402         M  ...                  0.07678          NaN
..        ...       ...  ...                      ...          ...
564    926424         M  ...                  0.07115          NaN
565    926682         M  ...                  0.06637          NaN
566    926954         M  ...                  0.07820          NaN
567    927241         M  ...                  0.12400          NaN
568     92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [76]:
# Drop the column that has NaN values
Cancer_data = data.dropna(axis='columns')
Cancer_data

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0      842302         M  ...          0.4601                  0.11890
1      842517         M  ...          0.2750                  0.08902
2    84300903         M  ...          0.3613                  0.08758
3    84348301         M  ...          0.6638                  0.17300
4    84358402         M  ...          0.2364                  0.07678
..        ...       ...  ...             ...                      ...
564    926424         M  ...          0.2060                  0.07115
565    926682         M  ...          0.2572                  0.06637
566    926954         M  ...          0.2218                  0.07820
567    927241         M  ...          0.4087                  0.12400
568     92751         B  ...          0.2871                  0.07039

[569 rows x 32 columns]

**Split the data into train and test sets**

In [77]:
# Define our features and targets
X = Cancer_data.drop(['diagnosis','id'],axis=1) 
y = np.where(Cancer_data['diagnosis']=='M',0,1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) # notice that we are suing the same random state number for the purpose of comparing the performance later


# Initialize the scaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


**Train the Model**

Before we actually code this, Let's look at the various parameters of the MPLClassifier class.
When defining MLP, we might consider tuning some parameter because MLP is not meant to work right out of the box so the results might be dissapointing.

In the previous session, we saw that for MLP to work we need to define the architecture of the neurons. well, that's just one parameter we can tune. There are a couple other parameters we can play with to make sure that we get the best out of the model.
Here are some of the paramters


*   **Solver** : This just refers to the gradient descent we want to use in the network. MLP gives us three options;
  1.   **SDG** - This is our good old stochastic gradient descent. When using SGD we also need to define the **learning rate**. if we do not define it, it has a default value of 0.001.
  2.   **adam** - This is a stochastic gradient based optimizer. It does well when you have a large dataset. You can read more on it in the link provided in the suggested reading section. It is said to have the best perfomance out of the three

  1.   **lbfgs** - an optimizer in the family of quasi-Newton methods.


*   **Activation**: Here we get to define the type of activation function we want to use in our network. we can use either one of the following;

      1.   **logistic** - used for the sigmoid function
      2.   **tanh** - used for the hyperbolic tan function
      1.   **relu** - used for the recttified linear unit

*   **alpha**: In MLP, this is the penalty term. Just like in svm where we denoted our penalty term as c. It helps regulate cases of overfitting.

*   **Learning_rate**: This is the learning rate for our SDG. It also has parameters;

      1.   **Constant** - refers to a constant learning rate given by learning_rate_init
      1.   **invscaling** - it will gradually decrease the learning rate at every step
      2.   **adaptive** - this means that the network will keep the learning_rate constant  to the learning_rate _init as long as the training loss keeps decreasing



*   **Learning_rate_init**: This is the initial learning rate used. If not declared, the network uses a default value of .001. This parameter is only used when solver is set to either  sdg or adam



* **Max_iter**: This indicates the number of iterations. In other words, this is determines the number of epoch.

**Note**: Every time you want to increase the accuracy of your model, these are the paramters you will tune 

Now let's get some code done.







In [78]:
# Creating our model
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30), activation='logistic', random_state=10, max_iter=500)
mlp.fit(X_train,y_train)

# Sometimes, depending on the number of iteration convergence might no be reached. When this happens just play around with your 
#max_iteration parameter.To see this in action put your max_iter to the default value of 200 and see what happens

MLPClassifier(activation='logistic', alpha=0.0001, batch_size='auto',
              beta_1=0.9, beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(30, 30, 30), learning_rate='constant',
              learning_rate_init=0.001, max_fun=15000, max_iter=500,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=10, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

**Prediction and Evaluation**

In [79]:
# Predicting
y_pred = mlp.predict(X_test)

# Evaluation
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))


[[45  2]
 [ 1 66]]
              precision    recall  f1-score   support

           0       0.98      0.96      0.97        47
           1       0.97      0.99      0.98        67

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



**Observation/Conclusion**

From our evaluation, we can conclude that only 2 tumors were misclassified giving us an accuracy score of 96%. This result is acceptable. 

Try tuning your parameters to see if you'll get an even better result than we've gotten right now.

Lastly, if we were to compare the performance of this model to the performance of the SVM model that we did a while back on the same dataset we can see that Neural Networks have a better performance than the SVM model. This is because using SVM we got an accuracy of 95.6% while we've gotten an accuracy if 96% using Neural Network.


## <font color= green>Challenge 1</fonts>


In [80]:
# Lower back pain can be caused by a variety of problems with any parts of the complex, interconnected network of spinal muscles, nerves, bones, discs or tendons in the lumbar spine.
# An irritation or problem with any of these structures can cause lower back pain and/or pain that radiates or is referred to other parts of the body. 
# Many lower back problems also cause back muscle spasms, which don't sound like much but can cause severe pain and disability.
# While lower back pain is extremely common, the symptoms and severity of lower back pain vary greatly. 
# A simple lower back muscle strain might be excruciating enough to necessitate an emergency room visit, while a degenerating disc might cause only mild, intermittent discomfort
# Use the following dataset to classify a persons spine as either normal or abnormal
# Dataset Url -------> http://bit.ly/spine_data

spine = pd.read_csv('http://bit.ly/spine_data')
spine.head(3)

# Define our features and targets
X = spine.drop(['Class_att','Unnamed: 13'],axis=1) 
y = np.where(spine['Class_att']=='Abnormal',0,1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) # notice that we are suing the same random state number for the purpose of comparing the performance later


# Initialize the scaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


In [81]:
# Creating our model
#mlp = MLPClassifier(hidden_layer_sizes=(51,51,51), activation='tanh', random_state=10, max_iter=500)
mlp = MLPClassifier(hidden_layer_sizes=(51,51,51),learning_rate='invscaling', activation='tanh', random_state=10, max_iter=500)
mlp.fit(X_train,y_train)

# Predicting
y_pred = mlp.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))



[[37  6]
 [ 5 14]]
              precision    recall  f1-score   support

           0       0.88      0.86      0.87        43
           1       0.70      0.74      0.72        19

    accuracy                           0.82        62
   macro avg       0.79      0.80      0.79        62
weighted avg       0.83      0.82      0.82        62



## <font color= green>Challenge 2</fonts>

In [82]:
# You are given a dataset that hava various traits of zoo animals and you are required to classify the animals into 7 classes:
# Mammal, Bird, Reptile, Fish, Amphibian, Bug and Invertebrate
# Use neural networks to achive this objective
# Dataset1 Url ----> http://bit.ly/zoo_data
# Dataset2 url-------http://bit.ly/zoo_class

dataset1 = pd.read_csv('http://bit.ly/zoo_data')
dataset2 = pd.read_csv('http://bit.ly/zoo_class')
dataset1.head(3)

animal_name  hair  feathers  eggs  ...  tail  domestic  catsize  class_type
0    aardvark     1         0     0  ...     0         0        1           1
1    antelope     1         0     0  ...     1         0        1           1
2        bass     0         0     1  ...     1         0        0           4

[3 rows x 18 columns]

In [83]:
dataset2.head(3)

Class_Number  ...                                       Animal_Names
0             1  ...  aardvark, antelope, bear, boar, buffalo, calf,...
1             2  ...  chicken, crow, dove, duck, flamingo, gull, haw...
2             3  ...    pitviper, seasnake, slowworm, tortoise, tuatara

[3 rows x 4 columns]

In [84]:
X = dataset1.drop(['class_type','animal_name'],axis =1)
y = dataset1['class_type']

X_train, X_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=0)


scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)


In [85]:
# Creating our model
mlp = MLPClassifier(hidden_layer_sizes=(20,20,20,20),learning_rate='invscaling', activation='tanh', random_state=10, max_iter=200)
mlp.fit(X_train,y_train)


/usr/local/lib/python3.6/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='tanh', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(20, 20, 20, 20), learning_rate='invscaling',
              learning_rate_init=0.001, max_fun=15000, max_iter=200,
              momentum=0.9, n_iter_no_change=10, nesterovs_momentum=True,
              power_t=0.5, random_state=10, shuffle=True, solver='adam',
              tol=0.0001, validation_fraction=0.1, verbose=False,
              warm_start=False)

In [86]:
# Predicting
y_pred = mlp.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))



[[7 0 0 0 0 0]
 [0 4 0 0 0 0]
 [0 0 5 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 2 0]
 [0 0 0 0 0 2]]
              precision    recall  f1-score   support

           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         5
           5       1.00      1.00      1.00         1
           6       1.00      1.00      1.00         2
           7       1.00      1.00      1.00         2

    accuracy                           1.00        21
   macro avg       1.00      1.00      1.00        21
weighted avg       1.00      1.00      1.00        21

